name: PolarAlerts
version: 1.0
main: dev.briiqn.polaralerts.PolarAlerts
api-version: 1.13
softdepend: [PolarLoader]
authors: [briiqn]
description: Helper plugin that forwards Polar alerts to BungeeCord

permissions:
  polaralerts.admin:
    description: Gives access to all PolarAlerts commands
    default: op
  anticheat.alerts:
    description: Allows users to see anticheat alerts
    default: op